df = read.csv("E:/dataclear")
str(df)
str(df$Brand)
summary(df)
hist(df$Price, breaks=50, col="green", xlab="Prices", xlim=c(8800000,50000000), main="Histogram of Price")
hist(df$ScrSize,breaks=50,col="blue", xlab="Size of screen")
barplot(table(df$Brand), main="th???ng kê theo  Brand")
barplot(table(df$RAM), main=" Th???ng kê theoo Ram")
barplot(table(df$GraphicCard))

barplot(table(df$OperSystem), main="Th???ng kê theo OP")
pie(table(df$Brand))
plot(df$ScrSize, df$Price, xlab="Size of screen",ylab="Price")
plot(df$RAM,df$Price, xlab='RAM',ylab='Price')
